export const moveSizeOptionsMap = {
    'House': [
      'One Item',
      'Just a Few Items',
      '2 Bedroom',
      '3 Bedroom',
      '4 Bedroom',
      '5 Bedroom',
      '6 Bedroom',
      '7 Bedroom',
      '8 Bedroom',
      '9+ Bedroom',
    ],
    'Town House': [
      'One Item',
      'Just a Few Items',
      '2 Bedroom',
      '3 Bedroom',
      '4 Bedroom',
      '5 Bedroom',
      '6 Bedroom',
      '7 Bedroom',
      '8 Bedroom',
      '9+ Bedroom',
    ],
    'Apartment': [
      'One Item',
      'Just a Few Items',
      '2 Bedroom',
      '3 Bedroom',
      '4 Bedroom',
      '5 Bedroom',
      '6 Bedroom',
      '7 Bedroom',
      '8 Bedroom',
      '9+ Bedroom',
    ],
    'Outdoor Storage': [
      'One Item',
      'Just a Few Items',
      '5X5',
      '5X10',
      '5X15',
      '10X10',
      '10X15',
      '10X20',
      '10X25',
      '10X30',
      '20X30',
      '30X30',
    ],
    'Indoor Storage': [
      'One Item',
      'Just a Few Items',
      '5X5',
      '5X10',
      '5X15',
      '10X10',
      '10X15',
      '10X20',
      '10X25',
      '10X30',
      '20X30',
      '30X30',
    ],
    'Office': [
      'One Item',
      'Just a Few Items',
      '1-5 People',
      '6-10 People',
      '11-20 People',
      '21-50 People',
      '51-100 People',
      '101-200 People',
      '201+ People',
    ],
    'Store': [
      'One Item',
      'Just a Few Items',
      'Small ( limited inventory )',
      'Medium ( moderate inventory )',
      'Large ( extensive inventory )',
      'Extra Large ( multiple departments )',
    ],
    'Religious Institution': [
      'One Item',
      'Just a Few Items',
      'Small ( basic furniture, minimal equipment )',
      'Medium ( more furniture, some equipment )',
      'Large ( multiple rooms, artifacts )',
      'Extra Large ( large-scale, specialized equipment )',
    ],
    'Government Institution': [
      'One Item',
      'Just a Few Items',
      'Small ( limited items )',
      'Medium ( more furniture, some specialized )',
      'Large ( multiple departments, extensive equipment )',
      'Extra Large ( large-scale, advanced equipment )',
    ],
    'Pod': [
      'One Item',
      'Just a Few Items',
      'Small ( up to 7 ft )',
      'Medium ( up to 12 ft )',
      'Large ( over 13 ft )',
    ],
    'Truck': [
      'One Item',
      'Just a Few Items',
      'Small ( up to 15 ft )',
      'Medium ( up to 22 ft )',
      'Large ( up to 32 ft )',
      'Extra Large ( up to 72 ft )',
    ],
    'Pickup Truck': [
      'One Item',
      'Just a Few Items',
      'Small Bed (5 ft)',
      'Standard Bed (6.5 ft)',
      'Long Bed (8 ft)',
    ],
    'Trailer': [
      'One Item',
      'Just a Few Items',
      'Small ( up to 15 ft )',
      'Medium ( up to 22 ft )',
      'Large ( up to 32 ft )',
      'Extra Large ( up to 53 ft )',
    ],
    'Container': [
      'One Item',
      'Just a Few Items',
      'Small ( up to 15 ft )',
      'Medium ( up to 22 ft )',
      'Large ( up to 40 ft )',
    ],
    'Van': [
      'One Item',
      'Just a Few Items',
      'Cargo Van',
      'Mini Van',
    ],
  };
  
  /**
   * A list of possible "typeOfPlace".
   */
  export const typeOfPlaceOptions = [
    'House',
    'Town House',
    'Apartment',
    'Outdoor Storage',
    'Indoor Storage',
    'Office',
    'Store',
    'Religious Institution',
    'Government Institution',
    'Pod',
    'Truck',
    'Pickup Truck',
    'Trailer',
    'Container',
    'Van',
  ];
  
  /** Which "typeOfPlace" are eligible for "How Many Stories" */
  export const storiesEligibleTypes = new Set([
    'House',
    'Town House',
    'Apartment',
    'Office',
    'Store',
    'Religious Institution',
    'Government Institution',
  ]);
  
  export const howManyStoriesOptions = [
    'Single Story',
    'Two Story',
    'Three Story',
    'Four Stories',
    '5+ Stories',
  ];
  
  /** Which "typeOfPlace" are eligible for "Furnishing Style" beyond minimal. */
  export const furnishingEligibleTypes = new Set([
    'House',
    'Town House',
    'Apartment',
    'Office',
    'Store',
    'Religious Institution',
    'Government Institution',
  ]);
  
  export const allowedOriginFields = [
    'typeOfPlace',
    'moveSize',
    'howManyStories',
    'furnishingStyle',
    'features',
    'needsCOI',
  ];
  
  export const allowedDestinationFields = [
    'typeOfPlace',
    'howManyStories',
    'features',
    'needsCOI',
  ];