-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "moveInEstimateAdditionalServices" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateBalanceDue" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateDeposit" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateDiscount" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateFuelSurcharge" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateGrandTotal" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimatePacking" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimatePayment" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateQuote" DOUBLE PRECISION,
ADD COLUMN     "moveInEstimateValuation" DOUBLE PRECISION,
ADD COLUMN     "moveInHasInvoice" BOOLEAN DEFAULT false,
ADD COLUMN     "moveInInvoiceAdditionalServices" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceBalanceDue" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceDeposit" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceDiscount" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceFuelSurcharge" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceGrandTotal" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoicePacking" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoicePayment" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceQuote" DOUBLE PRECISION,
ADD COLUMN     "moveInInvoiceValuation" DOUBLE PRECISION,
ADD COLUMN     "moveInTypeOfQuote" TEXT;
