
export type LeadInput = {
    customerName: string;
    customerEmail: string;
    customerPhoneNumber: string;
    companyName: string;
    brandId?: string;
    source: string;
    serviceType: string;
    salesName?: string;
    estimator?: string | null;
    surveyDate?: string | null;
    surveyTime?: string | null;
    rateType?: string;
    leadStatus?: string;
    leadActivity?: string;
    nextAction?: string;
    isNew?: boolean;
    inventoryOption?: string;
    addStorage?: boolean;
    timePromised?: boolean;
    storageItems?: string;
    arrivalTime?: string;
    moveDate?: string | null;
    fromZip?: string | null;
    toZip?: string | null;
    assignSalesRep?: boolean;
    hasInvoice?: boolean;
    numMovers?: number;
    numTrucks?: number;
    hourlyRate?: number;
    travelTime?: string;
    movingMin?: string;
    estimateQuote?: number;
    estimateFuelSurcharge?: number;
    estimateValuation?: number;
    estimatePacking?: number;
    estimateAdditionalServices?: number;
    estimateDiscount?: number;
    estimateGrandTotal?: number;
    estimatePayment?: number;
    estimateBalanceDue?: number;
    volume?: number;
    weight?: number;
    pricePerCuft?: number;
    pricePerLbs?: number;
    minimumCuft?: number;
    minimumLbs?: number;
    pickupWindow?: string;
    earliestDeliveryDate?: string;
    deliveryWindow?: string;
    numPackers?: number;
    packingHourlyRate?: number;
    packingTravelTime?: string;
    packingMinimum?: string;
    packingMinHours?: string;
    packingMaxHours?: string;
    jobNumber?: number;
    deliveryDate?: string;
    etaRequest?: string;
    activeDay?: string;
    hasPackingDay?: boolean;
    minHours?: string;
    maxHours?: string;
  invoiceQuote?: number;
  invoiceFuelSurcharge?: number;
  invoiceValuation?: number;
  invoicePacking?: number;
  invoiceAdditionalServices?: number;
  invoiceDiscount?: number;
  invoiceGrandTotal?: number;
  invoicePayment?: number;
  invoiceBalanceDue?: number;
  };

  export type OriginInput = {
    address?: string;
    apt?: string;
    city?: string;
    state?: string;
    displayedRooms?: number[]
    itemsByRoom?: JSON,
    zipCode?: string;
    typeOfPlace?: string;
    moveSize?: string;
    howManyStories?: string;
    features?: string[];
    furnishingStyle?: string;
    needsCOI?: boolean;
    biggestTruckAccess?: string;
    shuttleTruckRequired?: boolean;
    parkingAccess?: string;
    distanceDoorTruck?: string;
    howManySteps?: string;
    terrainDoorTruck?: string;
    elevatorAtStop?: boolean;
    elevatorExclusive?: boolean;
    elevatorFloors?: string;
    elevatorSize?: string;
    whatsMoving?: string;
    packingOption?: string;
    itemsToBeTakenApart?: boolean;
    hoistItems?: boolean;
    craneNeeded?: boolean;
    blanketsOption?: string;
    additionalServices?: string[];
    timeRestriction?: boolean;
    timeRestrictionOption?: string;
    timeRestrictionType?: string;
    timeRestrictionStartTime?: string;
    timeRestrictionEndTime?: string;
    isActive?: boolean;
    isVisible?:boolean;
  };
  
  
  export type DestinationsInput = {
    address?: string;
    apt?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    typeOfPlace?: string;
    moveSize?: string;
    howManyStories?: string;
    features?: string[];
    furnishingStyle?: string;
    needsCOI?: boolean;
    biggestTruckAccess?: string;
    shuttleTruckRequired?: boolean;
    parkingAccess?: string;
    distanceDoorTruck?: string;
    howManySteps?: string;
    terrainDoorTruck?: string;
    elevatorAtStop?: boolean;
    elevatorExclusive?: boolean;
    elevatorFloors?: string;
    elevatorSize?: string;
    whatsMoving?: string;
    packingOption?: string;
    itemsToBeTakenApart?: boolean;
    hoistItems?: boolean;
    craneNeeded?: boolean;
    blanketsOption?: string;
    additionalServices?: string[];
    postStorage?: boolean;
    timeRestriction?: boolean;
    timeRestrictionOption?: string;
    timeRestrictionType?: string;
    timeRestrictionStartTime?: string;
    timeRestrictionEndTime?: string;
    isActive?: boolean;
    isVisible?: boolean;
  };
  
  export type FurnitureInput = {
    name: string;
    imageName: string;
    rooms?: number[];
    letters?: string[];
    cuft?: number;
    lbs?: number;
    search?: "Y" | "N";
    tags?: string[];
    notes?: string;
    packingType?: string;
    packingQuantity?: number;
    link?: string;
    uploadedImages?: string [];
    cameraImages?: string [];
    groupingKey?: string;
    autoAdded?: boolean;
    brandId?: string;
  };

  export type InventoryItemInput = {
    originId: string;               
    furnitureItemId: number;        
    roomId?: number;     
    name?: string;
    imageName?: string;
    letters?: string[];  
    search?: string;
    cuft?: number;
    lbs?: number;
    tags?: string[];
    notes?: string;
    packingNeeds?: Record<string, number>;
    link?: string;
    uploadedImages?: string [];
    cameraImages?: string [];
    groupingKey?: string;
    autoAdded?: boolean;
    count?:number;
  };

  
  
  
  
  
