-- AlterTable
ALTER TABLE "FurnitureItem" ALTER COLUMN "rooms" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "letters" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "cuft" DROP NOT NULL,
ALTER COLUMN "lbs" DROP NOT NULL,
ALTER COLUMN "search" DROP NOT NULL,
ALTER COLUMN "tags" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "packingQuantity" DROP NOT NULL,
ALTER COLUMN "packingType" DROP NOT NULL;
